export const USER_BLOG_GET_REQUEST = 'USER_BLOG_GET_REQUEST';
export const USER_BLOG_GET_SUCCESS = 'USER_BLOG_GET_SUCCESS';
export const USER_BLOG_GET_FAILURE = 'USER_BLOG_GET_FAILURE';

export const USER_BLOG_POST_REQUEST = 'USER_BLOG_POST_REQUEST';
export const USER_BLOG_POST_SUCCESS = 'USER_BLOG_POST_SUCCESS';
export const USER_BLOG_POST_FAILURE = 'USER_BLOG_POST_FAILURE';