export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';

export const WRITER_LOGIN_REQUEST = 'WRITER_LOGIN_REQUEST';
export const WRITER_LOGIN_SUCCESS = 'WRITER_LOGIN_SUCCESS';
export const WRITER_LOGIN_FAILURE = 'WRITER_LOGIN_FAILURE';
